In [1]:
from read_file import parse_file
import numpy as np

In [2]:
a, b, c, d = parse_file('Данные ЛР 02 (прогонка).txt', 19)

a = np.insert(a, 0, 0) # a[0] = 0    это чтобы дальше обобщить алгоритм для alpha и betta
c = np.append(c, 0)    # c[n] = 0    это чтобы дальше обобщить алгоритм для alpha и betta

print(a)
print(b)
print(c)
print(d)

[ 0.  2. -1.  1.  1.  0.  1.]
[ 104.   98.   88. -141.   81.   73.   67.]
[ 1.  0. -1.  1.  1.  1.  0.]
[ 22.  20.  19. -26.  16.  15.  13.]


In [21]:

rows = len(d)
alpha, betta, x = np.zeros(rows), np.zeros(rows), np.zeros(rows)

for k in range (rows):
    # прямая прогонка
    alpha[k] = -c[k]/(b[k]+a[k]*alpha[k-1])
    betta[k] = (d[k] - a[k]*betta[k-1])/(b[k]+a[k]*alpha[k-1])

for k in range (rows-1, -1, -1):
    # обратная прогонка
    x[k] = betta[k]
    if(k < rows-1):
        x[k] += alpha[k]*x[k+1]



In [22]:
A = np.zeros((rows, rows))
for i in range(rows):
    for j in range(rows):
        if i == j:
            A[i][j] = b[i]
        if i == j+1:
            A[i][j] = a[i]
        if i == j-1:
            A[i][j] = c[i]

print(np.dot(A,x))   # проверяем решение, сверяем с векторм d


[ 22.  20.  19. -26.  16.  15.  13.]


In [15]:
def Norm1(a):
    if a.ndim == 1:
        return np.sum(np.abs(a))
    else:
        return np.max(np.sum(np.abs(a), axis=0))

In [16]:
def NormInf(a):
    if a.ndim == 1: 
        return np.max(np.abs(a))
    else:
        return np.max(np.sum(np.abs(a), axis=1))  

In [23]:
# невязка
r = d - np.dot(A,x)
print(Norm1(r))
print(NormInf(r))

5.329070518200751e-15
3.552713678800501e-15


In [29]:
d += 0.01


In [30]:

rows = len(d)
alpha, betta, x = np.zeros(rows), np.zeros(rows), np.zeros(rows)

for k in range (rows):
    # прямая прогонка
    alpha[k] = -c[k]/(b[k]+a[k]*alpha[k-1])
    betta[k] = (d[k] - a[k]*betta[k-1])/(b[k]+a[k]*alpha[k-1])

for k in range (rows-1, -1, -1):
    # обратная прогонка
    x[k] = betta[k]
    if(k < rows-1):
        x[k] += alpha[k]*x[k+1]



In [31]:
A = np.zeros((rows, rows))
for i in range(rows):
    for j in range(rows):
        if i == j:
            A[i][j] = b[i]
        if i == j+1:
            A[i][j] = a[i]
        if i == j-1:
            A[i][j] = c[i]

print(np.dot(A,x))   # проверяем решение, сверяем с векторм d


[ 22.02  20.02  19.02 -25.98  16.02  15.02  13.02]


In [32]:
# невязка
r = d - np.dot(A,x)
print(Norm1(r))
print(NormInf(r))

7.105427357601002e-15
3.552713678800501e-15
